-- Tripify 数据库设计与迁移索引 / 2026-09-12
-- 本文件只包含注释，执行本文件不会创建或修改任何表。
-- 可执行迁移：supabase/migrations/20260911123531_shared_trip_core.sql
-- 状态：代码和隔离 PostgreSQL 测试已实现；未自动应用到远程 Supabase。
-- 请勿将本文件当作已经部署的 schema。上线前先检查远程已有同名对象。
--
-- 本批只有 6 张表（不包含 Supabase 自带 auth.users）：
--
-- public.trips
--   id uuid PK; created_by uuid -> auth.users; name; destination;
--   start_date/end_date date; timezone IANA; currency; budget_total numeric(12,2);
--   version bigint default 1; created_at/updated_at timestamptz.
--   日期含首尾，1–60 天是当前 MVP 操作边界，不是永久产品承诺。
--   日期非 infinite，结束不能早于开始；金额 0..9999999999.99。
--   timezone 通过 pg_timezone_names 触发器校验，不从界面语言推断。
--
-- public.trip_members
--   PK(trip_id,user_id); trip_id -> trips; user_id -> auth.users;
--   display_name; interests; dislikes; food_preferences; pace;
--   budget_limit nullable numeric(12,2); joined_at timestamptz.
--   不暴露 auth.users 或复制 email/password。显示名称绝不用于授权。
--   偏好属于该次行程，目前共享成员可读；真实偏好编辑留待单独的权限设计。
--   null budget_limit = 未填写；0 = 明确零。UI 当前按 0 展示空预算。
--
-- public.trip_activities
--   id uuid PK; trip_id -> trips; day_number; start_time time without time zone;
--   title; location_name; latitude nullable; longitude nullable;
--   google_place_id nullable; duration_minutes; estimated_cost numeric(12,2);
--   created_at/updated_at timestamptz.
--   经纬度必须同时有值/同时为空；Place ID 有值则必须有坐标。
--   Google 地点名称和用户活动标题分开。手动地点不猜测坐标。
--   日期 = trips.start_date + day_number - 1；RPC 检查范围。
--   演示用 x/y 不是经纬度，绝不落库。
--
-- public.chat_messages
--   id uuid PK; trip_id -> trips; user_id -> auth.users; content (1..2000);
--   message_type(user/system/ai/recommendation/proposal/alert);
--   client_message_id nullable uuid; created_at/updated_at timestamptz.
--   UNIQUE(trip_id,user_id,client_message_id) 保证重试幂等。
--   当前 RPC 强制 auth.uid() 和 user 类型；不能伪造 AI 消息或发送者。
--   当前客户端总是发送 client_message_id；同 ID 不同文本拒绝。
--
-- public.trip_versions
--   id uuid PK; trip_id -> trips; version bigint; actor_user_id -> auth.users;
--   change_type; summary; snapshot jsonb; created_at timestamptz.
--   UNIQUE(trip_id,version)。snapshot 只含 trip + activities，绝不含聊天或成员偏好。
--   change_type = trip.created/trip.updated/activity.added/activity.updated/activity.removed。
--   无变化的保存拒绝 NO_CHANGES，不生成噪声版本。没有恢复/回滚按钮。
--
-- public.trip_invites
--   id uuid PK; trip_id -> trips; created_by -> auth.users; token_hash;
--   expires_at; accepted_at nullable; created_at.
--   仅保存 SHA-256 摘要。64 位十六进制邀请码由两个随机 UUID 生成；
--   原始码只在创建响应中返回一次，客户端内存展示，不入本地布局存储。
--   单次使用，72 小时有效。已登录用户显式提交邀请码后接受。
--
-- 权限 / RLS：
--   6 表全部开启 RLS，authenticated 显式最小 SELECT。
--   创建者/成员可读行程、成员、活动、聊天、历史；外部用户全部不可读。
--   邀请元信息只有创建者可读，token_hash 不授予浏览器 SELECT。
--   authenticated/anon 无直接 INSERT/UPDATE/DELETE 权限。
--   创建者可修改行程/活动、邀请、移除他人；不能移除自己。
--   普通成员只读行程/活动/历史，可发送聊天，不具备行程编辑权。
--   所有授权使用 auth.uid()，不使用 email、display_name 或 user_metadata。
--
-- 公共 RPC（SECURITY INVOKER）：
--   trip_create(p_data,p_display_name)
--   trip_mutate(p_trip,p_expected_version,p_operation,p_entity,p_data)
--   trip_invite_create(p_trip)
--   trip_invite_accept(p_token,p_display_name)
--   trip_member_remove(p_trip,p_user)
--   trip_chat_send(p_trip,p_content,p_client_message_id)
--
-- 私有 schema tripify_private 不得加入 Data API 的 exposed schemas。
--   受限 SECURITY DEFINER 用于无递归 RLS 成员检查，以及禁止绕过事务 RPC 的写入。
--   明确空 search_path、逐项白名单字段、函数内 auth.uid() 检查和 EXECUTE GRANT。
--   不给浏览器直接执行历史记录 helper 的权限。
--   public 包装函数为 invoker，调用私有实现；正常请求无需 service-role key。
--
-- 事务：
--   行程创建 + 创建者成员 + version 1 历史原子提交。
--   变更先锁 trips 行，再验证 expectedVersion，修改实体、version+1、写历史。
--   任一步失败整笔回滚。旧版本报 VERSION_CONFLICT，不静默覆盖。
--   成员变化/聊天不递增 itinerary version，不存聊天快照。
--   邀请接受/移除按 trip -> invite 顺序锁定；发送与成员移除串行检查权限。
--
-- Realtime：
--   publication 存在时加入 trips/trip_members/trip_activities/chat_messages。
--   不修改 Supabase 受保护的 realtime schema 对象。
--   UI 断线/焦点恢复重新查询，并每 15 秒校验权限；移除后数据库立即拒绝读取。
--
-- 不新增：proposals/votes、组织、订单、支付、分账、地图缓存表、预算汇总表、向量表。
--   这些都不是本批真实功能。演示提案仍是独立内存 fixture。
--   panel order/width/open/collapsed/hidden 是 localStorage UI 偏好，不进这些表。
--
-- 验证：
--   scripts/shared-trip-db.test.cjs：PGlite PostgreSQL WASM，隔离 Auth role shim。
--   已覆盖 RLS、邀请码、消息幂等、版本冲突、失败原子回滚。
--   不等同原生 PostgreSQL 多连接并发或线上 Auth/PostgREST/Realtime 验证。
--   UI 及部署清单详见 docs/SHARED_MVP_IMPLEMENTATION.md。
--
-- 应用远程前仍需：
--   1. 明确授权、测试项目和已有 schema 兼容性；不要覆盖同名表。
--   2. 测试项目先迁移并运行 Supabase security/performance advisors。
--   3. 验证 Data API exposed schemas 不含 tripify_private。
--   4. 两个真实账号联测聊天、邀请、成员移除和并发版本写入。
--   5. 确认备份、保留及删除政策。当前不提供删除行程/账号功能。
